### ISSUE TITLE
plans for merging into mainline?

### ISSUE THREAD

**Issue by anarcat** [tmshlvck/linux#1]
are there any plans in merging this branch into mainline? i understand you must be very busy with shipping machines and everything, but it would seem better for everyone involved if the kernel was "unforked" or at least following some longterm release...

from what i can tell, the branch point is 984065055e6e39f8dd812529e11922374bd39352. which seems to be 4.5-rc1 ([according to github](https://github.com/torvalds/linux/commit/984065055e6e39f8dd812529e11922374bd39352)). is that accurate? that seems to have been released shortly after 4.4, which is too bad because 4.4 is now in "longterm" support mode, according to kernel.org...

**Comment by anarcat** [comment]
it seems i was incorrect: uname -a tells me the kernel is 4.4.13..

**Comment by tmshlvck** [comment]
Well, there is an effort to use only-slightly hacked mainline kernel in omnia-debian project. The upstreaming is quite complex thing but yes. At least there is the DTS (thanks to Uwe K-K) and remaining things will come.

In the meanwhile please see master-omnia branch. Any help with testing/upstreaming would be appreciated.
