### ISSUE TITLE
Update/sync with turris-os

### ISSUE THREAD

**Issue by einstux** [tmshlvck/linux#2]
Could you please update this to the 4.4.31, which is in turris os? I tried to find the source for the kernel in turris-os repo, but have not really succeded...

Thanks

**Comment by tmshlvck** [comment]
Well, there is an effort to use only-slightly hacked mainline kernel in omnia-debian project. The relation with TurrisOS kernel is hard to maintain because we use tons of OpenWRT/LEDE patches there...

Please see master-omnia branch.
